In [1]:
!mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 3.2295 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [2]:
!mamba install numpy

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.9487000000000698 seconds
All requested packages already installed.

In [3]:
import pandas as pd
import numpy as py

In [4]:
df = pd.read_csv('commodity_prices.csv')

In [165]:
df.shape

(780, 20)

In [5]:
df.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx',
       'wheat_mom_growth_pct', 'wheat_yoy_growth_pct', 'maize_mom_growth_pct',
       'maize_yoy_growth_pct', 'soybean_oil_mom_growth_pct',
       'soybean_oil_yoy_growth_pct'],
      dtype='str')

In [8]:
df.dtypes

date                                 str
soybean_oil_usd_mt               float64
maize_usd_mt                     float64
wheat_usd_mt                     float64
dap_fertiliser_usd_mt            float64
mop_potash_usd_mt                float64
wheat_usd_mt_mom_pct             float64
wheat_usd_mt_yoy_pct             float64
maize_usd_mt_mom_pct             float64
maize_usd_mt_yoy_pct             float64
soybean_oil_usd_mt_mom_pct       float64
soybean_oil_usd_mt_yoy_pct       float64
dap_fertiliser_usd_mt_mom_pct    float64
dap_fertiliser_usd_mt_yoy_pct    float64
mop_potash_usd_mt_mom_pct        float64
mop_potash_usd_mt_yoy_pct        float64
dap_to_wheat_ratio               float64
fertiliser_composite_idx         float64
dtype: object

In [9]:
df.head()

,date,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,soybean_oil_usd_mt_mom_pct,soybean_oil_usd_mt_yoy_pct,dap_fertiliser_usd_mt_mom_pct,dap_fertiliser_usd_mt_yoy_pct,mop_potash_usd_mt_mom_pct,mop_potash_usd_mt_yoy_pct,dap_to_wheat_ratio,fertiliser_composite_idx
0,1960-01-31,204.0,45.0,59.89,0.0,28.5,0.000,0.0,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,28.5
1,1960-02-29,201.0,44.0,60.99,0.0,28.5,1.837,0.0,-2.222,0.0,-1.471,0.0,0.0,0.0,0.0,0.0,0.0,28.5
2,1960-03-31,201.0,45.0,61.73,0.0,28.5,1.213,0.0,2.273,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,28.5
3,1960-04-30,207.0,45.0,60.99,0.0,28.5,-1.199,0.0,0.000,0.0,2.985,0.0,0.0,0.0,0.0,0.0,0.0,28.5
4,1960-05-31,209.0,48.0,57.69,0.0,28.5,-5.411,0.0,6.667,0.0,0.966,0.0,0.0,0.0,0.0,0.0,0.0,28.5

In [6]:
print("\nTotal Null Values:", df.isnull().sum().sum())

Total Null Values: 39

In [32]:
print(df.isnull().sum())

date                              0
soybean_oil_usd_mt                0
maize_usd_mt                      0
wheat_usd_mt                      0
dap_fertiliser_usd_mt            84
mop_potash_usd_mt                 0
wheat_usd_mt_mom_pct              1
wheat_usd_mt_yoy_pct             12
maize_usd_mt_mom_pct              1
maize_usd_mt_yoy_pct             12
soybean_oil_usd_mt_mom_pct        1
soybean_oil_usd_mt_yoy_pct       12
dap_fertiliser_usd_mt_mom_pct    85
dap_fertiliser_usd_mt_yoy_pct    96
mop_potash_usd_mt_mom_pct         1
mop_potash_usd_mt_yoy_pct        12
dap_to_wheat_ratio               84
fertiliser_composite_idx          0
dtype: int64

In [95]:
df['dap_fertiliser_usd_mt'] = df['dap_fertiliser_usd_mt'].fillna('0.0')

In [96]:
df['wheat_usd_mt_mom_pct'] = df['wheat_usd_mt_mom_pct'].fillna('0')

In [97]:
df['wheat_usd_mt_yoy_pct'] = df['wheat_usd_mt_yoy_pct'].fillna('0')

In [100]:
df['maize_usd_mt_mom_pct'] = df['maize_usd_mt_mom_pct'].fillna('0.0')

In [99]:
df['maize_usd_mt_yoy_pct'] = df['maize_usd_mt_yoy_pct'].fillna('0.0')

In [101]:
df['soybean_oil_usd_mt_mom_pct'] = df['soybean_oil_usd_mt_mom_pct'].fillna('0')

In [102]:
df['soybean_oil_usd_mt_yoy_pct'] = df['soybean_oil_usd_mt_yoy_pct'].fillna('0')

In [103]:
df['dap_fertiliser_usd_mt_mom_pct'] = df['dap_fertiliser_usd_mt_mom_pct'].fillna('0')

In [104]:
df['dap_fertiliser_usd_mt_yoy_pct'] = df['dap_fertiliser_usd_mt_yoy_pct'].fillna('0')

In [115]:
df['mop_potash_usd_mt_mom_pct'] = df['mop_potash_usd_mt_mom_pct'].fillna('0')

In [116]:
df['mop_potash_usd_mt_yoy_pct'] = df['mop_potash_usd_mt_yoy_pct'].fillna('0')

In [107]:
df['dap_to_wheat_ratio'] = df['dap_to_wheat_ratio'].fillna('0')

In [167]:
print(df.isnull().sum())

date                              0
soybean_oil_usd_mt                0
maize_usd_mt                      0
wheat_usd_mt                      0
dap_fertiliser_usd_mt             0
mop_potash_usd_mt                 0
wheat_usd_mt_mom_pct              0
wheat_usd_mt_yoy_pct              0
maize_usd_mt_mom_pct              0
maize_usd_mt_yoy_pct              0
soybean_oil_usd_mt_mom_pct        0
soybean_oil_usd_mt_yoy_pct        0
dap_fertiliser_usd_mt_mom_pct     0
dap_fertiliser_usd_mt_yoy_pct     0
mop_potash_usd_mt_mom_pct         0
mop_potash_usd_mt_yoy_pct         0
dap_to_wheat_ratio                0
fertiliser_composite_idx          0
wheat_mom_growth_pct              1
wheat_yoy_growth_pct             12
dtype: int64

In [10]:
print("\nNumber of Duplicate Rows:", df.duplicated().sum())

Number of Duplicate Rows: 0

In [11]:
Avg_wheat_price = df['wheat_usd_mt'].mean()
print(Avg_wheat_price)

163.37815338846315

In [12]:
Avg_maize_price = df['maize_usd_mt'].mean()
print(Avg_maize_price)

126.47880683023354

In [13]:
Avg_fertilizer_index = df['fertiliser_composite_idx'].mean()
print(Avg_fertilizer_index)

194.4178717948718

In [14]:
import pandas as pd

# make sure date is in datetime format
df['date'] = pd.to_datetime(df['date'])

# sort by date = df.sort_values('date')
commodity_prices = df.sort_values('date')

# Month over Month growth % for wheat price
df['wheat_mom_growth_pct'] = df['wheat_usd_mt'].pct_change() * 100

# Year over Year growth % for wheat price
df['wheat_yoy_growth_pct'] = df['wheat_usd_mt'].pct_change(12) * 100

print(df[['date', 'wheat_usd_mt', 'wheat_mom_growth_pct', 'wheat_yoy_growth_pct']].head(780))

          date  wheat_usd_mt  wheat_mom_growth_pct  wheat_yoy_growth_pct
0   1960-01-31         59.89                   NaN                   NaN
1   1960-02-29         60.99              1.836701                   NaN
2   1960-03-31         61.73              1.213314                   NaN
3   1960-04-30         60.99             -1.198769                   NaN
4   1960-05-31         57.69             -5.410723                   NaN
..         ...           ...                   ...                   ...
775 2024-08-31        250.85             -3.615615            -20.571845
776 2024-09-30        269.69              7.510464            -14.297064
777 2024-10-31        272.85              1.171716             -8.470312
778 2024-11-30        253.75             -7.000183            -10.509610
779 2024-12-31        252.17             -0.622660            -13.379362

[780 rows x 4 columns]

In [15]:
df['date'] = pd.to_datetime(df['date'])
commodity_prices = df.sort_values('date')
df['maize_mom_growth_pct'] = df['maize_usd_mt'].pct_change() * 100
df['maize_yoy_growth_pct'] = df['maize_usd_mt'].pct_change(12) * 100
print(df[['date', 'maize_usd_mt', 'maize_mom_growth_pct', 'maize_yoy_growth_pct']].head(780))

          date  maize_usd_mt  maize_mom_growth_pct  maize_yoy_growth_pct
0   1960-01-31     45.000000                   NaN                   NaN
1   1960-02-29     44.000000             -2.222222                   NaN
2   1960-03-31     45.000000              2.272727                   NaN
3   1960-04-30     45.000000              0.000000                   NaN
4   1960-05-31     48.000000              6.666667                   NaN
..         ...           ...                   ...                   ...
775 2024-08-31    170.324757             -4.004108            -17.958144
776 2024-09-30    184.967154              8.596752            -17.354199
777 2024-10-31    190.335722              2.902444            -17.495177
778 2024-11-30    201.331060              5.776813             -4.700092
779 2024-12-31    202.597570              0.629068             -1.912615

[780 rows x 4 columns]

In [16]:
df['date'] = pd.to_datetime(df['date'])
commodity_prices = df.sort_values('date')
df['soybean_oil_mom_growth_pct'] = df['soybean_oil_usd_mt'].pct_change() * 100
df['soybean_oil_yoy_growth_pct'] = df['soybean_oil_usd_mt'].pct_change(12) * 100
print(df[['date', 'soybean_oil_usd_mt', 'soybean_oil_mom_growth_pct', 'soybean_oil_yoy_growth_pct']].head(780))

          date  soybean_oil_usd_mt  soybean_oil_mom_growth_pct  \
0   1960-01-31          204.000000                         NaN
1   1960-02-29          201.000000                   -1.470588
2   1960-03-31          201.000000                    0.000000
3   1960-04-30          207.000000                    2.985075
4   1960-05-31          209.000000                    0.966184
..         ...                 ...                         ...
775 2024-08-31         1031.380000                   -4.415117
776 2024-09-30         1043.810000                    1.205181
777 2024-10-31         1094.890000                    4.893611
778 2024-11-30         1145.170570                    4.592294
779 2024-12-31         1063.631006                   -7.120299

     soybean_oil_yoy_growth_pct
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN
..                          ...
775                   -8.446291
776                   -6.100951
777                   -3.437784
778                    2.394565
779                    0.108332

[780 rows x 4 columns]

In [17]:
df['wheat_mom_growth_pct'] = df['wheat_mom_growth_pct'].fillna('0')
df['wheat_yoy_growth_pct'] = df['wheat_yoy_growth_pct'].fillna('0')
df['maize_mom_growth_pct'] = df['maize_mom_growth_pct'].fillna('0')
df['maize_yoy_growth_pct'] = df['maize_yoy_growth_pct'].fillna('0')
df['soybean_oil_mom_growth_pct'] = df['soybean_oil_mom_growth_pct'].fillna('0')
df['soybean_oil_yoy_growth_pct'] = df['soybean_oil_yoy_growth_pct'].fillna('0')

In [18]:
df.to_csv("commodity_prices.csv", index=False)

In [14]:
df = pd.read_csv('crop_yields.csv')

In [10]:
df.shape

(64, 11)

In [15]:
df.columns

Index(['year', 'maize_area_mha', 'maize_production_mt', 'rice_paddy_area_mha',
       'rice_paddy_production_mt', 'wheat_area_mha', 'wheat_production_mt',
       'wheat_production_mt_yoy_pct', 'rice_paddy_production_mt_yoy_pct',
       'maize_production_mt_yoy_pct', 'total_staple_production_mt'],
      dtype='str')

In [16]:
df.dtypes

year                                  int64
maize_area_mha                      float64
maize_production_mt                 float64
rice_paddy_area_mha                 float64
rice_paddy_production_mt            float64
wheat_area_mha                      float64
wheat_production_mt                 float64
wheat_production_mt_yoy_pct         float64
rice_paddy_production_mt_yoy_pct    float64
maize_production_mt_yoy_pct         float64
total_staple_production_mt          float64
dtype: object

In [17]:
df.head()

,year,maize_area_mha,maize_production_mt,rice_paddy_area_mha,rice_paddy_production_mt,wheat_area_mha,wheat_production_mt,wheat_production_mt_yoy_pct,rice_paddy_production_mt_yoy_pct,maize_production_mt_yoy_pct,total_staple_production_mt
0,1961,105559.547,205027.236,115365.128,215646.627,204209.450,222357.231,0.000,0.000,0.000,643031.094
1,1962,103496.472,204876.636,119452.412,226456.291,207554.518,250319.146,12.575,5.013,-0.073,681652.073
2,1963,108427.427,220228.115,120151.874,247119.204,206130.240,233339.473,-6.783,9.124,7.493,700686.792
3,1964,107925.069,215172.391,125056.092,262928.949,216539.177,268791.657,15.193,6.398,-2.296,746892.997
4,1965,106676.499,226544.121,124828.866,254059.657,216979.762,263645.963,-1.914,-3.373,5.285,744249.741

In [37]:
print(df.isnull().sum())

year                                0
maize_area_mha                      0
maize_production_mt                 0
rice_paddy_area_mha                 0
rice_paddy_production_mt            0
wheat_area_mha                      0
wheat_production_mt                 0
wheat_production_mt_yoy_pct         1
rice_paddy_production_mt_yoy_pct    1
maize_production_mt_yoy_pct         1
total_staple_production_mt          0
dtype: int64

In [115]:
df['wheat_production_mt_yoy_pct'] = df['wheat_production_mt_yoy_pct'].fillna('0.0')

In [116]:
df['rice_paddy_production_mt_yoy_pct'] = df['rice_paddy_production_mt_yoy_pct'].fillna('0')

In [117]:
df['maize_production_mt_yoy_pct'] = df['maize_production_mt_yoy_pct'].fillna('0')

In [18]:
print(df.isnull().sum())

year                                0
maize_area_mha                      0
maize_production_mt                 0
rice_paddy_area_mha                 0
rice_paddy_production_mt            0
wheat_area_mha                      0
wheat_production_mt                 0
wheat_production_mt_yoy_pct         0
rice_paddy_production_mt_yoy_pct    0
maize_production_mt_yoy_pct         0
total_staple_production_mt          0
dtype: int64

In [119]:
print("\nNumber of Duplicate Rows:", df.duplicated().sum())

Number of Duplicate Rows: 0

In [19]:
df.to_csv("crop_yields.csv", index=False)

In [130]:
df = pd.read_csv('food_security_panel.csv')

In [131]:
df.shape

(420, 38)

In [132]:
df.columns

Index(['date', 'soybean_oil_usd_mt', 'maize_usd_mt', 'wheat_usd_mt',
       'dap_fertiliser_usd_mt', 'mop_potash_usd_mt', 'wheat_usd_mt_mom_pct',
       'wheat_usd_mt_yoy_pct', 'maize_usd_mt_mom_pct', 'maize_usd_mt_yoy_pct',
       'soybean_oil_usd_mt_mom_pct', 'soybean_oil_usd_mt_yoy_pct',
       'dap_fertiliser_usd_mt_mom_pct', 'dap_fertiliser_usd_mt_yoy_pct',
       'mop_potash_usd_mt_mom_pct', 'mop_potash_usd_mt_yoy_pct',
       'dap_to_wheat_ratio', 'fertiliser_composite_idx',
       'undernourishment_pct', 'food_production_index', 'cereal_yield_kg_ha',
       'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg',
       'ffpi_overall', 'ffpi_cereals', 'ffpi_overall_mom_pct',
       'ffpi_cereals_yoy_pct', 'ffpi_above_baseline', 'ffpi_crisis_flag',
       'dap_to_wheat_elevated', 'ffpi_volatility_12m',
       'cereals_affordability_idx', 'supply_stress_flag', 'food_shock_score',
       'month', 'year'],
      dtype='str')

In [22]:
df.dtypes

date                                 str
soybean_oil_usd_mt               float64
maize_usd_mt                     float64
wheat_usd_mt                     float64
dap_fertiliser_usd_mt            float64
mop_potash_usd_mt                float64
wheat_usd_mt_mom_pct             float64
wheat_usd_mt_yoy_pct             float64
maize_usd_mt_mom_pct             float64
maize_usd_mt_yoy_pct             float64
soybean_oil_usd_mt_mom_pct       float64
soybean_oil_usd_mt_yoy_pct       float64
dap_fertiliser_usd_mt_mom_pct    float64
dap_fertiliser_usd_mt_yoy_pct    float64
mop_potash_usd_mt_mom_pct        float64
mop_potash_usd_mt_yoy_pct        float64
dap_to_wheat_ratio               float64
fertiliser_composite_idx         float64
undernourishment_pct             float64
food_production_index            float64
cereal_yield_kg_ha               float64
arable_land_pct                  float64
undernourishment_pct_yoy_chg     float64
food_production_index_yoy_chg    float64
cereal_yield_kg_ha_yoy_chg       float64
ffpi_overall                     float64
ffpi_cereals                     float64
ffpi_overall_mom_pct             float64
ffpi_cereals_yoy_pct             float64
ffpi_above_baseline                int64
ffpi_crisis_flag                   int64
dap_to_wheat_elevated              int64
ffpi_volatility_12m              float64
cereals_affordability_idx        float64
supply_stress_flag                 int64
food_shock_score                   int64
month                              int64
year                               int64
dtype: object

In [133]:
df.head()

,date,soybean_oil_usd_mt,maize_usd_mt,wheat_usd_mt,dap_fertiliser_usd_mt,mop_potash_usd_mt,wheat_usd_mt_mom_pct,wheat_usd_mt_yoy_pct,maize_usd_mt_mom_pct,maize_usd_mt_yoy_pct,...,ffpi_cereals_yoy_pct,ffpi_above_baseline,ffpi_crisis_flag,dap_to_wheat_elevated,ffpi_volatility_12m,cereals_affordability_idx,supply_stress_flag,food_shock_score,month,year
0,31-01-1990,417.0,105.60,167.92,138.500,98.500,2.011,-3.383,-3.270,-10.660,...,NaN,0,0,0,NaN,145.43,0,0,1,1990
1,28-02-1990,428.0,106.07,160.94,139.750,98.500,-4.157,-6.408,0.445,-9.666,...,NaN,0,0,0,NaN,148.61,0,0,2,1990
2,31-03-1990,442.0,109.70,156.53,146.000,97.375,-2.740,-12.165,3.422,-7.332,...,NaN,0,0,0,NaN,148.52,0,0,3,1990
3,30-04-1990,440.0,118.82,159.47,155.200,93.200,1.878,-8.629,8.314,2.661,...,NaN,0,0,0,NaN,141.60,0,0,4,1990
4,31-05-1990,449.0,121.04,149.18,149.125,93.500,-6.453,-15.416,1.868,2.890,...,NaN,0,0,0,NaN,145.12,0,0,5,1990

In [39]:
print(df.isnull().sum())

date                               0
soybean_oil_usd_mt                 0
maize_usd_mt                       0
wheat_usd_mt                       0
dap_fertiliser_usd_mt              0
mop_potash_usd_mt                  0
wheat_usd_mt_mom_pct               0
wheat_usd_mt_yoy_pct               0
maize_usd_mt_mom_pct               0
maize_usd_mt_yoy_pct               0
soybean_oil_usd_mt_mom_pct         0
soybean_oil_usd_mt_yoy_pct         0
dap_fertiliser_usd_mt_mom_pct      0
dap_fertiliser_usd_mt_yoy_pct      0
mop_potash_usd_mt_mom_pct          0
mop_potash_usd_mt_yoy_pct          0
dap_to_wheat_ratio                 0
fertiliser_composite_idx           0
undernourishment_pct             144
food_production_index             37
cereal_yield_kg_ha                 1
arable_land_pct                   13
undernourishment_pct_yoy_chg     156
food_production_index_yoy_chg     37
cereal_yield_kg_ha_yoy_chg         1
ffpi_overall                       0
ffpi_cereals                       0
ffpi_overall_mom_pct               1
ffpi_cereals_yoy_pct              12
ffpi_above_baseline                0
ffpi_crisis_flag                   0
dap_to_wheat_elevated              0
ffpi_volatility_12m               12
cereals_affordability_idx          0
supply_stress_flag                 0
food_shock_score                   0
month                              0
year                               0
dtype: int64

In [134]:
df['undernourishment_pct'] = df['undernourishment_pct'].fillna('0')

In [135]:
df['food_production_index'] = df['food_production_index'].fillna('0')

In [136]:
df['cereal_yield_kg_ha'] = df['cereal_yield_kg_ha'].fillna('0')

In [137]:
df['arable_land_pct'] = df['arable_land_pct'].fillna('0')

In [138]:
df['undernourishment_pct_yoy_chg'] = df['undernourishment_pct_yoy_chg'].fillna('0')

In [139]:
df['food_production_index_yoy_chg'] = df['food_production_index_yoy_chg'].fillna('0')

In [140]:
df['cereal_yield_kg_ha_yoy_chg'] = df['cereal_yield_kg_ha_yoy_chg'].fillna('0')

In [141]:
df['ffpi_overall_mom_pct'] = df['ffpi_overall_mom_pct'].fillna('0')

In [142]:
df['ffpi_cereals_yoy_pct'] = df['ffpi_cereals_yoy_pct'].fillna('0')

In [143]:
df['ffpi_volatility_12m'] = df['ffpi_volatility_12m'].fillna('0')

In [24]:
print(df.isnull().sum())

date                             0
soybean_oil_usd_mt               0
maize_usd_mt                     0
wheat_usd_mt                     0
dap_fertiliser_usd_mt            0
mop_potash_usd_mt                0
wheat_usd_mt_mom_pct             0
wheat_usd_mt_yoy_pct             0
maize_usd_mt_mom_pct             0
maize_usd_mt_yoy_pct             0
soybean_oil_usd_mt_mom_pct       0
soybean_oil_usd_mt_yoy_pct       0
dap_fertiliser_usd_mt_mom_pct    0
dap_fertiliser_usd_mt_yoy_pct    0
mop_potash_usd_mt_mom_pct        0
mop_potash_usd_mt_yoy_pct        0
dap_to_wheat_ratio               0
fertiliser_composite_idx         0
undernourishment_pct             0
food_production_index            0
cereal_yield_kg_ha               0
arable_land_pct                  0
undernourishment_pct_yoy_chg     0
food_production_index_yoy_chg    0
cereal_yield_kg_ha_yoy_chg       0
ffpi_overall                     0
ffpi_cereals                     0
ffpi_overall_mom_pct             0
ffpi_cereals_yoy_pct             0
ffpi_above_baseline              0
ffpi_crisis_flag                 0
dap_to_wheat_elevated            0
ffpi_volatility_12m              0
cereals_affordability_idx        0
supply_stress_flag               0
food_shock_score                 0
month                            0
year                             0
dtype: int64

In [124]:
print("\nNumber of Duplicate Rows:", df.duplicated().sum())

Number of Duplicate Rows: 0

In [145]:
Avg_food_price_index = df['ffpi_overall'].mean()
print(Avg_food_price_index)

94.08240476190477

In [146]:
crisis_count = df['ffpi_crisis_flag'].sum()
print(crisis_count)

82

In [147]:
supply_stress_count = df['supply_stress_flag'].sum()
print(supply_stress_count)

54

In [149]:
df.to_csv("food_security_panel.csv", index=False)

In [150]:
df = pd.read_csv('food_security_indicators.csv')

In [151]:
df.shape

(63, 8)

In [152]:
df.columns

Index(['year', 'undernourishment_pct', 'food_production_index',
       'cereal_yield_kg_ha', 'arable_land_pct', 'undernourishment_pct_yoy_chg',
       'food_production_index_yoy_chg', 'cereal_yield_kg_ha_yoy_chg'],
      dtype='str')

In [39]:
df.dtypes

year                               int64
undernourishment_pct             float64
food_production_index            float64
cereal_yield_kg_ha               float64
arable_land_pct                  float64
undernourishment_pct_yoy_chg     float64
food_production_index_yoy_chg    float64
cereal_yield_kg_ha_yoy_chg       float64
dtype: object

In [40]:
df.head()

,year,undernourishment_pct,food_production_index,cereal_yield_kg_ha,arable_land_pct,undernourishment_pct_yoy_chg,food_production_index_yoy_chg,cereal_yield_kg_ha_yoy_chg
0,1961,NaN,12.899822,NaN,NaN,NaN,NaN,NaN
1,1962,NaN,13.174495,NaN,NaN,NaN,0.275,NaN
2,1963,NaN,13.789956,NaN,9.642818,NaN,0.615,NaN
3,1964,NaN,13.510396,1576.946325,9.663356,NaN,-0.280,NaN
4,1965,NaN,13.635739,1625.014969,9.694099,NaN,0.125,48.069

In [41]:
print(df.isnull().sum())

year                              0
undernourishment_pct             40
food_production_index             3
cereal_yield_kg_ha                3
arable_land_pct                   3
undernourishment_pct_yoy_chg     41
food_production_index_yoy_chg     4
cereal_yield_kg_ha_yoy_chg        4
dtype: int64

In [153]:
df['undernourishment_pct'] = df['undernourishment_pct'].fillna('0')

In [154]:
df['food_production_index'] = df['food_production_index'].fillna('0')

In [155]:
df['cereal_yield_kg_ha'] = df['cereal_yield_kg_ha'].fillna('0')

In [156]:
df['arable_land_pct'] = df['arable_land_pct'].fillna('0')

In [157]:
df['undernourishment_pct_yoy_chg'] = df['undernourishment_pct_yoy_chg'].fillna('0')

In [158]:
df['food_production_index_yoy_chg'] = df['food_production_index_yoy_chg'].fillna('0')

In [159]:
df['cereal_yield_kg_ha_yoy_chg'] = df['cereal_yield_kg_ha_yoy_chg'].fillna('0')

In [160]:
print(df.isnull().sum())

year                             0
undernourishment_pct             0
food_production_index            0
cereal_yield_kg_ha               0
arable_land_pct                  0
undernourishment_pct_yoy_chg     0
food_production_index_yoy_chg    0
cereal_yield_kg_ha_yoy_chg       0
dtype: int64

In [51]:
print("\nNumber of Duplicate Rows:", df.duplicated().sum())

Number of Duplicate Rows: 0

In [161]:
df.to_csv("food_security_indicators.csv", index=False)